    services:
      # Сервис для базы данных (PostgreSQL)
      db:
        image: postgres:13
        environment:
          POSTGRES_USER: darthundeddu
          POSTGRES_PASSWORD: 6713
          POSTGRES_DB: archangel
        volumes:
          - postgres_data:/var/lib/postgresql/data
        networks:
          - backend

      # Сервис для Django с Gunicorn
      archangel:
        build: .
        command: gunicorn Archangel.wsgi:application --bind 0.0.0.0:5000
        volumes:
          - .:/app
        expose:
          - "5000"  # Используем expose, потому что проксирование будет через NGINX
        depends_on:
          - db
        networks:
          - backend

      # Сервис для NGINX
      nginx:
        build:
          context: ./nginx
          dockerfile: Dockerfile
        container_name: nginx
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - /home/darthundeddu/pki:/etc/nginx/ssl
          - ./staticfiles:/usr/share/nginx/html/static
          # - media:/usr/share/nginx/html/media
        depends_on:
          - archangel
        networks:
          - backend

    volumes:
      postgres_data:
      static:
      media:

    networks:
      backend:
